#version: '3.8'

services:
  app:
    container_name: inventory-db-mysql
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: price_list_part_diesel
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
